# Generated by Django 4.0.4 on 2023-04-18 23:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('date', models.CharField(max_length=100)),
                ('place', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('lastname', models.CharField(max_length=100)),
                ('firstname', models.CharField(max_length=100)),
                ('patronymic', models.CharField(max_length=100)),
                ('school', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('phone', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Timetable',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('time', models.DateTimeField()),
                ('place', models.CharField(max_length=100)),
                ('host', models.CharField(max_length=100)),
                ('seats', models.IntegerField(default=-1)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='regsys.event')),
            ],
        ),
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='regsys.guest')),
                ('timetable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='regsys.timetable')),
            ],
        ),
    ]
