# Generated by Django 4.0.4 on 2023-04-19 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regsys', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guest',
            name='firstname',
        ),
        migrations.RemoveField(
            model_name='guest',
            name='lastname',
        ),
        migrations.RemoveField(
            model_name='guest',
            name='patronymic',
        ),
        migrations.AddField(
            model_name='guest',
            name='name',
            field=models.CharField(default='name', max_length=200),
            preserve_default=False,
        ),
    ]
