# Generated by Django 4.2 on 2023-05-03 13:53

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('regsys', '0002_remove_guest_firstname_remove_guest_lastname_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'verbose_name': 'Событие', 'verbose_name_plural': 'События'},
        ),
        migrations.AlterModelOptions(
            name='guest',
            options={'verbose_name': 'Участник', 'verbose_name_plural': 'Участники'},
        ),
        migrations.AlterModelOptions(
            name='registration',
            options={'verbose_name': 'Запись', 'verbose_name_plural': 'Записи'},
        ),
        migrations.AlterModelOptions(
            name='timetable',
            options={'verbose_name': 'Расписание', 'verbose_name_plural': 'Расписание'},
        ),
        migrations.RemoveField(
            model_name='timetable',
            name='time',
        ),
        migrations.AddField(
            model_name='timetable',
            name='annotation',
            field=models.CharField(default='annotation or what', max_length=1000, verbose_name='Аннотация'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='timetable',
            name='category',
            field=models.CharField(default='category', max_length=100, verbose_name='Категория'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='timetable',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Дата'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='timetable',
            name='repeating',
            field=models.BooleanField(default=False, verbose_name='Повторяющееся?'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.CharField(max_length=100, verbose_name='Даты'),
        ),
        migrations.AlterField(
            model_name='event',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='Номер'),
        ),
        migrations.AlterField(
            model_name='event',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='event',
            name='place',
            field=models.CharField(max_length=100, verbose_name='Место'),
        ),
        migrations.AlterField(
            model_name='guest',
            name='email',
            field=models.EmailField(max_length=100, verbose_name='Почта'),
        ),
        migrations.AlterField(
            model_name='guest',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='Номер'),
        ),
        migrations.AlterField(
            model_name='guest',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='guest',
            name='phone',
            field=models.CharField(max_length=100, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='guest',
            name='school',
            field=models.CharField(max_length=100, verbose_name='Место обучения'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='guest',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='regsys.guest', verbose_name='Участник'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='timetable',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='regsys.timetable', verbose_name='Событие'),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='regsys.event', verbose_name='Событие'),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='host',
            field=models.CharField(max_length=100, verbose_name='Ведущий'),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='Номер'),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='place',
            field=models.CharField(max_length=100, verbose_name='Место'),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='seats',
            field=models.IntegerField(default=-1, verbose_name='Свободных мест'),
        ),
    ]
