# Generated by Django 4.2 on 2023-05-04 07:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regsys', '0004_event_annotation_alter_timetable_repeating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='date',
        ),
        migrations.AddField(
            model_name='event',
            name='end_date',
            field=models.DateField(default=datetime.datetime(2023, 5, 4, 7, 49, 38, 849106, tzinfo=datetime.timezone.utc), verbose_name='Последний день'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='start_date',
            field=models.DateField(default=datetime.datetime(2023, 5, 4, 7, 49, 50, 318127, tzinfo=datetime.timezone.utc), verbose_name='Первый день'),
            preserve_default=False,
        ),
    ]
