# Generated by Django 4.2 on 2023-05-06 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regsys', '0005_remove_event_date_event_end_date_event_start_date'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='event',
            constraint=models.CheckConstraint(check=models.Q(('end_date__gte', models.F('start_date'))), name='end_date_check'),
        ),
    ]
