# Generated by Django 4.2 on 2023-05-08 22:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('regsys', '0007_remove_event_end_date_check_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='registration',
            name='reg_unique',
        ),
    ]
