# Generated by Django 4.2 on 2023-05-11 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regsys', '0008_remove_registration_reg_unique'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='event',
            name='early_end_date_check',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='name',
            new_name='event_name',
        ),
        migrations.RenameField(
            model_name='timetable',
            old_name='name',
            new_name='timetable_name',
        ),
        migrations.RemoveField(
            model_name='guest',
            name='name',
        ),
        migrations.AddField(
            model_name='guest',
            name='guest_name',
            field=models.CharField(default='name', max_length=200, verbose_name='Имя'),
            preserve_default=False,
        ),
    ]
