# Generated by Django 4.2 on 2023-08-06 10:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('regsys', '0009_remove_event_early_end_date_check_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guest',
            name='guest_name',
        ),
        migrations.AddField(
            model_name='guest',
            name='birthday',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Дата рождения'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='guest',
            name='firstname',
            field=models.CharField(default='e', max_length=100, verbose_name='Имя'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='guest',
            name='password',
            field=models.CharField(default='password', max_length=50, verbose_name='Пароль'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='guest',
            name='patronymic',
            field=models.CharField(default='ee', max_length=100, verbose_name='Отчество'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='guest',
            name='surname',
            field=models.CharField(default='e', max_length=100, verbose_name='Фамилия'),
            preserve_default=False,
        ),
    ]
