# Generated by Django 4.2 on 2023-08-06 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regsys', '0010_remove_guest_guest_name_guest_birthday_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guest',
            name='email',
            field=models.EmailField(max_length=100, verbose_name='Электронная почта'),
        ),
        migrations.AlterField(
            model_name='guest',
            name='phone',
            field=models.CharField(max_length=100, verbose_name='Номер телефона'),
        ),
    ]
