# Generated by Django 4.2 on 2023-08-10 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('regsys', '0013_remove_guest_email_remove_guest_password_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guest',
            name='birthday',
        ),
    ]
