# Generated by Django 4.2 on 2023-08-12 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regsys', '0014_remove_guest_birthday'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='status',
            field=models.CharField(choices=[('Подтверждено', 'Aff'), ('Отклонено', 'Dec'), ('В листе ожидания', 'Wai'), ('Посещено', 'Vis'), ('Пропущено', 'Ski')], default='Подтверждено', verbose_name='Статус'),
        ),
    ]
