# Generated by Django 4.2 on 2023-08-12 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regsys', '0015_registration_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='status',
            field=models.CharField(choices=[('AFF', 'Подтверждено'), ('DEC', 'Отклонено'), ('WAI', 'В листе ожидания'), ('VIS', 'Посещено'), ('SKI', 'Пропущено')], default='AFF', verbose_name='Статус'),
        ),
    ]
