# Generated by Django 4.2 on 2023-08-12 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regsys', '0016_alter_registration_status'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='event',
            constraint=models.UniqueConstraint(fields=('event_name',), name='unique name'),
        ),
    ]
