# Generated by Django 4.2 on 2023-11-15 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regsys', '0021_label_labelmap'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='labelmap',
            options={'verbose_name': 'Лейблмап', 'verbose_name_plural': 'Лейблмап'},
        ),
        migrations.AddField(
            model_name='guest',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Фото'),
        ),
        migrations.AddField(
            model_name='guest',
            name='telegram',
            field=models.CharField(default='aboba', max_length=100, verbose_name='Ник в телеграме'),
            preserve_default=False,
        ),
    ]
