# Generated by Django 4.2 on 2023-11-18 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regsys', '0022_alter_labelmap_options_guest_photo_guest_telegram'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guest',
            name='photo',
        ),
        migrations.AlterField(
            model_name='guest',
            name='telegram',
            field=models.CharField(max_length=100, verbose_name='Телеграм'),
        ),
    ]
