# Generated by Django 4.2 on 2024-05-16 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regsys', '0024_remove_timetable_seats_timetable_seats_all_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timetable',
            name='seats_available',
        ),
        migrations.AddField(
            model_name='timetable',
            name='seats_taken',
            field=models.IntegerField(default=0, editable=False, verbose_name='Занято мест'),
        ),
    ]
