# Generated by Django 4.2.13 on 2024-05-23 12:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('regsys', '0025_remove_timetable_seats_available_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tagmap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='regsys.event', verbose_name='Событие')),
            ],
            options={
                'verbose_name': 'Тег для события',
                'verbose_name_plural': 'Теги событий',
            },
        ),
        migrations.RenameModel(
            old_name='Label',
            new_name='Tag',
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'verbose_name': 'Тег', 'verbose_name_plural': 'Теги'},
        ),
        migrations.AlterModelOptions(
            name='timetable',
            options={'verbose_name': 'Элемент расписания', 'verbose_name_plural': 'Элементы расписания'},
        ),
        migrations.RenameField(
            model_name='tag',
            old_name='label_name',
            new_name='tag_name',
        ),
        migrations.AlterField(
            model_name='registration',
            name='status',
            field=models.CharField(choices=[('AFF', 'Еще не посещено'), ('INT', 'Пересекается'), ('WAI', 'Очередь'), ('VIS', 'Посещено'), ('MIS', 'Пропущено')], default='AFF', verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='category',
            field=models.CharField(help_text='*в категорию входит время проведения мероприятия (11.00-12.00) или его время и тип (14.00-15.00, обед); для корректности отображения расписания важно вводить время в одном формате', max_length=100, verbose_name='Категория'),
        ),
        migrations.DeleteModel(
            name='Labelmap',
        ),
        migrations.AddField(
            model_name='tagmap',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='regsys.tag', verbose_name='Тег'),
        ),
    ]
