# Generated by Django 4.2.13 on 2024-05-26 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regsys', '0026_tagmap_alter_tag_options_alter_timetable_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='tag_name',
            field=models.CharField(max_length=50, unique=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='category',
            field=models.CharField(help_text='* в категорию входит время проведения мероприятия (11.00-12.00) или его время и тип (14.00-15.00, обед); для корректности отображения расписания важно вводить время в одном формате', max_length=100, verbose_name='Категория'),
        ),
    ]
